In [1]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_excel("/Users/ahmadasdo/Library/Containers/com.microsoft.Excel/Data/Downloads/Maintenance Central File V7 20210121.xlsm")

In [12]:
df

,No.,Project,Date,Date Issue Closed,Rate Urgency,Component,Installation / Component,Task Carried Out By,Details,Status,...,Unnamed: 12,Lists,% Loss Due To Error,Action / Result,Report Copy/Paste Table,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,0,+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Status,NaN,Analysis performed / no significant losses / N...,Date,Urgency,Component,Engineer,Status,Details
1,0,Aerosud,2019-09-16 00:00:00,2019-09-16 00:00:00,Low,PV System,Installation,Natheera,System online. System 1,Closed,...,NaN,Open,NaN,Charl to fix,2019-09-16 00:00:00,Low,PV System,Natheera,Closed,System online. System 1
2,0,Aerosud,2019-09-11 00:00:00,2019-09-11 00:00:00,Low,PV System,Installation,Natheera,System online. System 2,Closed,...,NaN,Closed,NaN,Charl inspected site and will have to return,2019-09-11 00:00:00,Low,PV System,Natheera,Closed,System online. System 2
3,0,Aerosud,2019-10-18 00:00:00,2019-10-24 00:00:00,High,Monitoring,Installation,David,System 2 offline due to communication fault. C...,Closed,...,NaN,NaN,NaN,Reconnect - Connection re-established,2019-10-18 00:00:00,High,Monitoring,David,Closed,System 2 offline due to communication fault. C...
4,0,Aerosud,2019-10-06 00:00:00,2019-10-06 00:00:00,Low,PV System,Installation,Natheera,PV modules cleaned,Closed,...,NaN,Component,NaN,Connection back with network renaming,2019-10-06 00:00:00,Low,PV System,Natheera,Closed,PV modules cleaned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
1268,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
1269,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
1270,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN
1271,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN

In [13]:
df.shape

(1272, 22)

In [15]:
df.dtypes

No.                           int64
Project                      object
Date                         object
Date Issue Closed            object
Rate Urgency                 object
Component                    object
Installation / Component     object
Task Carried Out By          object
Details                      object
Status                       object
Internal details             object
Unnamed: 11                 float64
Unnamed: 12                  object
Lists                        object
% Loss Due To Error          object
Action / Result              object
Report Copy/Paste Table      object
Unnamed: 17                  object
Unnamed: 18                  object
Unnamed: 19                  object
Unnamed: 20                  object
Unnamed: 21                  object
dtype: object

In [16]:
df.columns

Index(['No.', 'Project', 'Date', 'Date Issue Closed', 'Rate Urgency',
       'Component', 'Installation / Component', 'Task Carried Out By',
       'Details ', 'Status', 'Internal details', 'Unnamed: 11', 'Unnamed: 12',
       'Lists', '% Loss Due To Error', 'Action / Result',
       'Report Copy/Paste Table', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21'],
      dtype='object')

In [17]:
df.fillna(0)

,No.,Project,Date,Date Issue Closed,Rate Urgency,Component,Installation / Component,Task Carried Out By,Details,Status,...,Unnamed: 12,Lists,% Loss Due To Error,Action / Result,Report Copy/Paste Table,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,0,+,0,0,0,0,0,0,0,0,...,0,Status,0,Analysis performed / no significant losses / N...,Date,Urgency,Component,Engineer,Status,Details
1,0,Aerosud,2019-09-16 00:00:00,2019-09-16 00:00:00,Low,PV System,Installation,Natheera,System online. System 1,Closed,...,0,Open,0,Charl to fix,2019-09-16 00:00:00,Low,PV System,Natheera,Closed,System online. System 1
2,0,Aerosud,2019-09-11 00:00:00,2019-09-11 00:00:00,Low,PV System,Installation,Natheera,System online. System 2,Closed,...,0,Closed,0,Charl inspected site and will have to return,2019-09-11 00:00:00,Low,PV System,Natheera,Closed,System online. System 2
3,0,Aerosud,2019-10-18 00:00:00,2019-10-24 00:00:00,High,Monitoring,Installation,David,System 2 offline due to communication fault. C...,Closed,...,0,0,0,Reconnect - Connection re-established,2019-10-18 00:00:00,High,Monitoring,David,Closed,System 2 offline due to communication fault. C...
4,0,Aerosud,2019-10-06 00:00:00,2019-10-06 00:00:00,Low,PV System,Installation,Natheera,PV modules cleaned,Closed,...,0,Component,0,Connection back with network renaming,2019-10-06 00:00:00,Low,PV System,Natheera,Closed,PV modules cleaned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1268,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1269,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1270,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1271,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

NameError: name 'df_Lists' is not defined